apiVersion: apps/v1
kind: Deployment
metadata:
  name: supergraph-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supergraph-gateway
  template:
    metadata:
      labels:
        app: supergraph-gateway
    spec:
      containers:
        - name: supergraph-gateway
          image: ghcr.io/mostofakamal/apollographql/supergraph-gateway:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
---
apiVersion: v1
kind: Service
metadata:
  name: supergraph-gateway
spec:
  type: LoadBalancer
  selector:
    app: supergraph-gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
