apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-dgs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-dgs
  template:
    metadata:
      labels:
        app: product-dgs
    spec:
      containers:
        - name: product-dgs
          image: ghcr.io/mostofakamal/apollographql/product-dgs:latest
          ports:
            - containerPort: 4002
          env:
            - name: PORT
              value: "4002"
---
apiVersion: v1
kind: Service
metadata:
  name: product-dgs
spec:
  type: LoadBalancer
  selector:
    app: product-dgs
  ports:
    - protocol: TCP
      port: 4002
      targetPort: 4002
